### ISSUE TITLE
Update description link

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/nodejs-news-feeder#14]
<img width="445" alt="Captura de pantalla 2023-06-22 a las 15 42 35" src="https://github.com/nodejs/news-feeder/assets/5110813/540ac28b-2b3b-4d6b-b6d7-1ad716809710">

Current repo link is poting to the old url. The correct URL should be https://raw.githubusercontent.com/nodejs/news-feeder/main/feed.xml

I don't have the permissions

**Comment by mhdawson** [comment]
updated - https://nodejs.github.io/nodejs-news-feeder/feed.xml

**Comment by UlisesGascon** [comment]
thanks @mhdawson!
