### ISSUE TITLE
Idea: Top threads of the week/month

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/nodejs-news-feeder#42]
Note: sorry, hit enter on accident on the first try.

What if we scanned the project issues for active/popular issues/prs and automatically put together a "this week in node.js" threads list.

**Comment by wesleytodd** [comment]
from @bnb: https://github.com/cutenode/retro-weekly/tree/main

**Comment by bnb** [comment]
that also uses retrogen: https://github.com/cutenode/retrogen

**Comment by wesleytodd** [comment]
Honestly, even if we didn't have more investment what you have there @bnb is probably worthy of publishing as is. At least it would give the "firehose" update folks might be interested in.

**Comment by bnb** [comment]
@wesleytodd happy to either copy or set up the configuration of my tool for Node.js. It's pretty easy.

**Comment by wesleytodd** [comment]
Would love to hear @UlisesGascon's opinion. To me it seems like an easy win to add an entry to the RSS feed each week linking to your current generated stuff.

**Comment by UlisesGascon** [comment]
Thanks for this great suggestion! I made a PR for it https://github.com/nodejs/nodejs-news-feeder/pull/51. Let me know what you think :)
