### ISSUE TITLE
RSS feed is out of order

### ISSUE THREAD

**Issue by vcarl** [nodejs/nodejs-news-feeder#99]
Items in the [published RSS feed](https://nodejs.github.io/nodejs-news-feeder/feed.xml) are non-chronological, which is causing an issue for me with an RSS<>Discord connector that seems to presume that the first post will always be the most recent

<img width="297" alt="Screenshot 2024-07-29 at 2 30 25 PM" src="https://github.com/user-attachments/assets/c89de7af-257f-4240-8b52-34b1a4b9f2f8">

**Comment by ovflowd** [comment]
cc @UlisesGascon

**Comment by UlisesGascon** [comment]
Thanks for reporting this! I will work on it.
